name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        example: [examples/tx-simple/main_tx.cpp, examples/tx-analog/main_tx_analog.cpp, examples/rx-simple/main_rx.cpp, examples/pass-through/main_passthru.cpp]
        special-example: [examples/rx-lcd/main_rx_lcd.cpp]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO CI UNO
        run: pio ci --lib="." --board=uno
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_UNO
      
      - name: Run PlatformIO CI BLUEPILL
        run: pio ci --lib="." --board=bluepill_f103c8
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_BLUEPILL
      
      - name: Download external library
        run: |
          wget https://github.com/arduino-libraries/LiquidCrystal/archive/master.zip -O /tmp/LiquidCrystal.zip
          unzip /tmp/LiquidCrystal.zip -d /tmp

      - name: Run PlatformIO CI LCD
        run: pio ci --lib="." --lib="/tmp/LiquidCrystal" --board=uno --board=bluepill_f103c8
        env:
          PLATFORMIO_CI_SRC: ${{matrix.special-example}}
          PLATFORMIO_BUILD_FLAGS: -D BOARD_UNO
