name: Code style correction
permissions: write-all
on:
  push:
    branches:
      - main

jobs:
  astyle-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Install astyle
        run: sudo apt install astyle

      - name: Format code
        run: astyle -r **/*.cpp **/*.c **/*.h **/*.hpp

      - name: Create pull request
        run: |
          git add .
          git commit -am "Format code with astyle"
          git push origin HEAD
          gh pr create --title "Format code with astyle" --body ""